### ISSUE TITLE
How do i get rooms list?

### ISSUE THREAD

**Issue by essuraj** [wperw/node-red-contrib-socketio#11]
I need the list of rooms from the socket.. how do i acheive this in nodered?

**Comment by essuraj** [comment]
submitted a pull request. merging it and updating on npm is hightly appreciated

**Comment by wperw** [comment]
@essuraj Into next days I'll put all on NPM

**Comment by essuraj** [comment]
thankyou.. the sooner the better please.. i need if for my project :)

**Comment by wperw** [comment]
Hi, published on npm, thank you for your work
