### ISSUE TITLE
name "socketio-config" is also another nodered module node

### ISSUE THREAD

**Issue by j2l** [wperw/node-red-contrib-socketio#8]
you get a conflict when installing ["node-red-contrib-socketio-client](https://github.com/isaacvitor/node-red-contrib-socketio-client)"
Hence, you can uninstall any (clicking disable or remove does nothing):
![image](https://user-images.githubusercontent.com/65325/41997661-ec425816-7a58-11e8-8f21-5af14759e09f.png)

**Comment by wperw** [comment]
Hi, I've seen that you have published the same issue also on the other git node, but I've no idea to solve this issue and prevent the compatibility issiue for those that also use my node implementation.

**Comment by j2l** [comment]
Ok, thanks, never mind.
